### ISSUE TITLE
Atomicfu stabilization plan

### ISSUE THREAD

**Issue by mvicsokolova** [Kotlin/kotlinx-atomicfu#342]
This issue will track the progress of atomicfu stabilization.

✅ - Done
⏳ - Postponed for some reason
🛠️ - In progress
🟨 - Not started yet

## Roadmap REVIEWED:

**UPD 0.23.0 release:**
* **Native** compiler plugin will be enabled in kotlinx.coroutines: https://github.com/Kotlin/kotlinx.coroutines/pull/3942 ✅
* **JVM** compiler plugin is also enabled in kotlinx.coroutines. ✅

**After update to 1.9.20:** 

* **JVM**:  compiler plugin is enabled by default and may be turned off with a flag in atomicfu gradle extension, JVM bytecode transformer is deprecated and ready to be removed. ❌
    _JVM IR compiler plugin transformations are not enabled by default yet, because not all main atomicfu users migrated to compiler plugin transformations yet (e.g. ktor). There is WIP migrating all the projects to IR transformations._
* **Native**: compiler plugin may be enabled with a flag ✅.
* **JS**: compiler plugin may be enabled with a flag, legacy JS transformer is deprecated and ready to be removed. ➖
    _JS legacy transformer may be removed, because usage of JS Legacy target is an error since Kotlin 1.9.0._  _JS IR transformations were not enabled by default due to the remaining unresolved problems in the compiler plugin._ ❌

**After update to 2.0:**

* **JVM**: JVM bytecode transformer is removed.
* **JS**: legacy JS transformer is removed, compiler plugin is enabled by default.
* **Native**: compiler plugin is enabled by default.
_________________________________________________________________________________________________

## Update of the plan

I've updated the plan and restructured the focus a little. Here are the main priority tasks critical for stabilisation:

As it was stated previously `kotlinx-atomicfu` should get rid of bytecode legacy transformation and enable compiler plugin transformations by default. Prior to enabling compiler transformations by default, we should make sure that all major atomicfu users have compiler transformation already enabled, and figure out the reason if they still use legacy transformation. Here is the current status (more projects will be added).

1. Enable compiler plugin transformations: 

**kotlinx.coroutines** ([flags](https://github.com/Kotlin/kotlinx.coroutines/blob/8c516f5ab1fcc39629d2838489598135eedd7b80/gradle.properties#L48)):
JVM:  ✅
Native:  ✅
JS: ❌
- [ ]  incremental compilation bug (TODO: add a ticket here)

**Compose**  ([flags](https://github.com/JetBrains/compose-multiplatform-core/blob/d25515c3e12055ecf367cc82a5a354571e0925ff/gradle.properties#L112)):
JVM: ✅ 🛠️ (with WA)
Native: ✅
JS: ✅
- [ ] [KT-65645](https://youtrack.jetbrains.com/issue/KT-65645/Atomicfu-plugin-compilation-hangs-on-a-long-string-concatenation)

**ktor**  ([flags](https://github.com/ktorio/ktor/blob/14c25646d52169101c4ccd5a052b38bf1993d967/gradle.properties#L27)):
JVM: 🛠️
Native: 🛠️
JS: ❌

Here is the PR that enables JVM and Native compiler plugin transformations in ktor: https://github.com/ktorio/ktor/pull/4018

2. JVM bytecode transformation should be removed.

- [ ] https://github.com/Kotlin/kotlinx-atomicfu/issues/338 ⏳
     _Will be done when JVM IR transformations are enabled by default._

3. Plugin application should become easy and documented: 
- [ ] https://github.com/Kotlin/kotlinx-atomicfu/issues/56 🛠️
- [ ] https://github.com/Kotlin/kotlinx-atomicfu/issues/341 🟨
- [x] https://github.com/Kotlin/kotlinx-atomicfu/issues/399  ✅
- [x] https://github.com/Kotlin/kotlinx-atomicfu/issues/370 ✅
    Moving to the kotlin repo is postponed until compiler plugin transformations are not enabled by default. See the full resolution in the last comment of the issue.
   UPD: The current solution was to move the logic of the gradle plugin in kotlin repo to the library. See #406

4. **Documentation**:
- [ ] https://github.com/Kotlin/kotlinx-atomicfu/issues/368 🟨
_________________________________________________________________________________________________

And here is the backlog that should be steadily fixed as well:

**Compiler plugin:** 
Here is the backlog compiler plugin issues: [#kotlinx-atomicfu](https://youtrack.jetbrains.com/issues?q=Assignee:%20me%20%20tag:%20kotlinx-atomicfu%20State:%20Submitted%20State:%20Open)

**Library:**

- [ ] https://github.com/Kotlin/kotlinx-atomicfu/issues/324 🟨
- [ ] JS: get rid of `atomicfu-runtime` package in the compiler plugin: [KT-61611](https://youtrack.jetbrains.com/issue/KT-61611/atomicfu-JS-Get-rid-of-atomicfu-runtime-module-in-the-atomicfu-compiler-plugin) 🟨
- [ ] https://github.com/Kotlin/kotlinx-atomicfu/issues/362 🛠️
      _More integration tests were added for different project configurations._
- [ ] https://github.com/Kotlin/kotlinx-atomicfu/issues/387 🟨

**Comment by mvicsokolova** [comment]
This way of tracking the stabilization process was too hard to support, and was replaced by the GH Project.
